import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex items-center min-h-screen p-4 sm:pl-24 sm:pr-24 md:pl-20 md:pr-20  w-full h-full flex-col gap-8 bg-slate-950">
          {/* <Snowfall /> */}
          <div className="w-full h-full bg-slate-800 rounded-md pl-4  pr-4  text-white">
            <Header />
          </div>
          {children}
        </main>
      </body>
    </html>
  );
}
